INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMINISTRATOR');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('manager', 'ROLE_MANAGER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('dev1', 'ROLE_DEVELOPER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('dev2', 'ROLE_DEVELOPER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user1', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('user2', 'ROLE_USER');